// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMGAi2XZeRwMkmcrwChRzffbp4XBNg1bY',
    appId: '1:899334986632:android:43ec1a72d36565cade383d',
    messagingSenderId: '899334986632',
    projectId: 'valentine-app-9f402',
    storageBucket: 'valentine-app-9f402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVixsmFOdFJYNy9uZJp0BOdozViVj4ftM',
    appId: '1:899334986632:ios:dc357b00fe8a3d64de383d',
    messagingSenderId: '899334986632',
    projectId: 'valentine-app-9f402',
    storageBucket: 'valentine-app-9f402.firebasestorage.app',
    iosBundleId: 'com.cobyzero.valentineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVixsmFOdFJYNy9uZJp0BOdozViVj4ftM',
    appId: '1:899334986632:ios:dc357b00fe8a3d64de383d',
    messagingSenderId: '899334986632',
    projectId: 'valentine-app-9f402',
    storageBucket: 'valentine-app-9f402.firebasestorage.app',
    iosBundleId: 'com.cobyzero.valentineApp',
  );
}
